version: '3.8'
services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-manager
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    networks:
      - default
      - nginx_network
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  nginx_network:
    name: nginx_network
