version: '3.8'
services:
  db:
    image: postgres:14.6-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=lisbon_prod
    ports:
      - 5433:5432
    volumes: 
      - db:/var/lib/postgresql/data
  lisbon:
      image: dimamik/lisbon_${SYSTEM_VERSION}
      container_name: lisbon
      restart: always
      ports: 
        # I'm not sure if this is needed as we're forcing HTTPS connections
        - 80:80
        - 443:443
      depends_on:
        - db
      volumes:
        - ${HOST_CERT_FOLDER}:/app/cert
      env_file:
        - .env
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 lisbon
      
volumes:
  db:
    driver: local